trigger:
- main

pool:
  name: 'MySelfHostedPool'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  JAVA_HOME: 'C:\Program Files\Eclipse Adoptium\jdk-11.0.26.4-hotspot'

stages:
# BUILD STAGE
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - task: PowerShell@2
      displayName: 'Configure Java Environment'
      inputs:
        targetType: 'inline'
        failOnStderr: false
        errorActionPreference: 'continue'
        script: |
          Write-Host "Setting up Java environment"
          Write-Host "JAVA_HOME: $env:JAVA_HOME"
          
          # Add Java bin to PATH
          $env:PATH = "$env:PATH;$env:JAVA_HOME\bin"
          Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
          
          # Verify Java is accessible
          Write-Host "Java version:"
          java -version 2>&1 | ForEach-Object { Write-Host $_ }
    
    # Use the latest version of SonarCloud tasks (@3)
    - task: SonarCloudPrepare@3
      displayName: 'Prepare SonarCloud Analysis'
      inputs:
        SonarCloud: 'SonarCloud-Connection'
        organization: 'landonessex'
        scannerMode: 'dotnet'
        projectKey: 'landonessex_note-taking-app-devops'
        projectName: 'Note Taking App'
        extraProperties: |
          # Main source code locations only
          sonar.sources=Front-Desktop/notes-app/src,Noteworthy-Backend/Controllers,Noteworthy-Backend/Models,Noteworthy-Backend/Services
          
          # Comprehensive exclusions
          sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js,**/bin/**,**/obj/**,**/*.json,**/Properties/**,**/wwwroot/**
          
          # Define test files separately
          sonar.tests=**/Tests/**
          sonar.test.inclusions=**/*Test*/**,**/*.test.js,**/*.spec.js
          sonar.test.exclusions=**/node_modules/**,**/bin/**,**/obj/**
          
          # Additional configuration
          sonar.sourceEncoding=UTF-8
          sonar.log.level=DEBUG
          
          # Explicitly disable binary analysis to avoid dependencies conflicts
          sonar.dotnet.excludeTestProjects=true
    
    # Step 1: Build .NET Backend - COMPILE
    - task: DotNetCoreCLI@2
      displayName: 'Build .NET Backend'
      inputs:
        command: 'build'
        projects: '**/Noteworthy-Backend.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    # Step 2: Build Frontend - COMPILE
    - task: Npm@1
      displayName: 'Frontend - Install Dependencies'
      inputs:
        command: 'install'
        workingDir: 'Front-Desktop/notes-app'
    
    - task: Npm@1
      displayName: 'Frontend - Build'
      inputs:
        command: 'custom'
        workingDir: 'Front-Desktop/notes-app'
        customCommand: 'run build'
    
    # Use the latest version of SonarCloud tasks (@3)
    - task: SonarCloudAnalyze@3
      displayName: 'Run SonarCloud Analysis'
      timeoutInMinutes: 15
      env:
        SONAR_SCANNER_OPTS: "-Xmx2048m"
    
    # Use the latest version of SonarCloud tasks (@3)
    - task: SonarCloudPublish@3
      displayName: 'Publish SonarCloud Quality Gate'
      inputs:
        pollingTimeoutSec: '300'

# DELIVERY STAGE
- stage: Deliver
  displayName: 'Delivery Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeliverJob
    displayName: 'Package Artifact'
    steps:
    # Package .NET Backend
    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Backend'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/backend'
        zipAfterPublish: true
    
    # Package Frontend
    - task: CopyFiles@2
      displayName: 'Copy Frontend Files'
      inputs:
        SourceFolder: 'Front-Desktop/notes-app/build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
    
    # Publish Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# DEPLOY TO DEV STAGE
- stage: DeployToDev
  displayName: 'Deploy to Dev'
  dependsOn: Deliver
  condition: succeeded()
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy to Dev Environment'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Dev Environment"
              echo "Deploying Backend..."
              echo "Deploying Frontend..."
              # This is a mock deployment for demonstration
            displayName: 'Deploy to Dev'

# DEPLOY TO QAT STAGE
- stage: DeployToQAT
  displayName: 'Deploy to QAT'
  dependsOn: DeployToDev
  condition: succeeded()
  jobs:
  - deployment: DeployQAT
    displayName: 'Deploy to QAT Environment'
    environment: 'qat'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to QAT Environment"
              # Mock deployment
            displayName: 'Deploy to QAT'

# DEPLOY TO STAGING STAGE
- stage: DeployToStaging
  displayName: 'Deploy to Staging'
  dependsOn: DeployToQAT
  condition: succeeded()
  jobs:
  - deployment: DeployStaging
    displayName: 'Deploy to Staging Environment'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Staging Environment"
              # Mock deployment
            displayName: 'Deploy to Staging'

# DEPLOY TO PRODUCTION STAGE
- stage: DeployToProduction
  displayName: 'Deploy to Production'
  dependsOn: DeployToStaging
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    displayName: 'Deploy to Production Environment'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Production Environment"
              # Mock deployment
            displayName: 'Deploy to Production'
